---adding schema
---code to create table

CREATE TABLE Customer_appointments (
    Appointment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Patient_name VARCHAR(50) NOT NULL,
    Information_needed TEXT NOT NULL,
    Date_Of_Birth DATE NOT NULL,
    Date_Of_Appointment DATE NOT NULL CHECK (Date_Of_Appointment >= CURRENT_DATE),
    Address VARCHAR(255) NOT NULL,
    Phone_Number VARCHAR(15) NOT NULL UNIQUE,
    Gp VARCHAR(50) NOT NULL
);


---code ot insert data
INSERT INTO Customer_appointments
    (Patient_name, Information_needed, Date_Of_Birth, Date_Of_Appointment, Address, Phone_Number, Gp)
VALUES
    ('Alice Thompson', 'Follow-up for blood test results', '1988-04-12', '2025-12-10', '12 Meadow Lane, Shrewsbury SY1 3AA', '07123456780', 'Dr. Sarah Patel'),
    ('Benjamin Carter', 'New patient registration', '1992-09-25', '2025-12-12', '44 Brook Street, Shrewsbury SY2 6BT', '07123456781', 'Dr. James O''Connor'),
    ('Charlotte Evans', 'Repeat prescription review', '1979-01-07', '2025-12-15', '8 Oak Drive, Shrewsbury SY3 7QD', '07123456782', 'Dr. Emily Wright'),
    ('Daniel Hughes', 'Annual health check', '1985-06-19', '2025-12-18', '21 Riverside Close, Shrewsbury SY1 4LP', '07123456783', 'Dr. Michael Green'),
    ('Ella Robinson', 'Flu vaccination appointment', '2001-11-03', '2025-12-20', '5 Church Road, Shrewsbury SY2 5DN', '07123456784', 'Dr. Priya Shah'),
    ('Freddie Wilson', 'Physio referral discussion', '1995-03-14', '2025-12-22', '73 Quarry View, Shrewsbury SY3 8HE', '07123456785', 'Dr. Daniel Morris'),
    ('Grace Bennett', 'Asthma review and action plan', '2000-02-28', '2025-12-27', '19 Parkside Avenue, Shrewsbury SY1 2JG', '07123456786', 'Dr. Helen Clarke'),
    ('Harry Morgan', 'Travel vaccines consultation', '1983-08-09', '2025-12-29', '2 Mill Court, Shrewsbury SY2 6PU', '07123456787', 'Dr. Robert King'),
    ('Isla Turner', 'Skin rash assessment', '1998-12-30', '2026-01-02', '56 Spring Gardens, Shrewsbury SY3 9LT', '07123456788', 'Dr. Anna Hughes'),
    ('Jack Peterson', 'Diet and lifestyle advice', '1975-07-22', '2026-01-05', '10 Station Way, Shrewsbury SY1 1AB', '07123456789', 'Dr. Charlotte Reed');
